Repository LaboratoireMecaniqueLille/crappy, pull requests merged in 2023-11, with the labels that each got.

#71 Enhancement of the parameters management for the opencv camera
  CODEOWNERS
  src/crappy/camera/__init__.py
  src/crappy/camera/_v4l2_base.py
  src/crappy/camera/gstreamer_camera_basic.py
  src/crappy/camera/gstreamer_camera_v4l2.py
  src/crappy/camera/opencv_camera_basic.py
  src/crappy/camera/opencv_camera_v4l2.py
  src/crappy/camera/opencv_camera_webcam.py
Labels: enhancement

#77 Update packaging-related files
  MANIFEST.in
  pyproject.toml
  requirements.txt
  setup.py
Labels: structure, update

#76 Enhancement of the format detection in camera gstreamer basic
  src/crappy/camera/gstreamer_camera_basic.py
  src/crappy/camera/gstreamer_camera_v4l2.py
Labels: enhancement

#79 Release of Crappy version 2.0.0
  docs/source/conf.py
  setup.py
  src/crappy/__version__.py
  src/crappy/blocks/_deprecated.py
  src/crappy/blocks/client_server.py
  src/crappy/blocks/pid.py
  src/crappy/blocks/stop_block.py
  src/crappy/camera/gstreamer_camera_v4l2.py
  src/crappy/modifier/__init__.py
  src/crappy/modifier/_deprecated.py
  src/crappy/tool/camera_config/camera_config.py
  src/crappy/tool/camera_config/config_tools/histogram_process.py
Labels: bug, enhancement, update
