Repository LaboratoireMecaniqueLille/crappy, pull requests merged in 2023-10, with the labels that each got.

#45 Reset Block after cleanup
  docs/source/developers.rst
  src/crappy/blocks/meta_block/block.py
Labels: enhancement

#46 Feature/Runtime order check in Block
  docs/source/developers.rst
  src/crappy/blocks/meta_block/block.py
Labels: bug, enhancement

#48 Add button to auto apply settings in the configuration window
  src/crappy/tool/camera_config/camera_config.py
Labels: enhancement

#49 Allow custom overlay on Camera Displayer
  docs/source/crappy_docs/tools.rst
  src/crappy/blocks/camera.py
  src/crappy/blocks/camera_processes/camera_process.py
  src/crappy/blocks/camera_processes/dic_ve.py
  src/crappy/blocks/camera_processes/dis_correl.py
  src/crappy/blocks/camera_processes/display.py
  src/crappy/blocks/camera_processes/gpu_ve.py
  src/crappy/blocks/camera_processes/video_extenso.py
  src/crappy/blocks/gpu_correl.py
  src/crappy/tool/camera_config/__init__.py
  src/crappy/tool/camera_config/config_tools/__init__.py
  src/crappy/tool/camera_config/config_tools/box.py
  src/crappy/tool/camera_config/config_tools/overlay_object.py
Labels: enhancement

#50 Make it more user-friendly to instantiate custom Camera Blocks
  docs/source/crappy_docs/blocks.rst
  src/crappy/blocks/camera.py
  src/crappy/blocks/camera_processes/camera_process.py
  src/crappy/blocks/camera_processes/dic_ve.py
  src/crappy/blocks/camera_processes/dis_correl.py
  src/crappy/blocks/camera_processes/display.py
  src/crappy/blocks/camera_processes/gpu_correl.py
  src/crappy/blocks/camera_processes/gpu_ve.py
  src/crappy/blocks/camera_processes/record.py
  src/crappy/blocks/camera_processes/video_extenso.py
  src/crappy/blocks/dic_ve.py
  src/crappy/blocks/dis_correl.py
  src/crappy/blocks/gpu_correl.py
  src/crappy/blocks/gpu_ve.py
  src/crappy/blocks/video_extenso.py
Labels: enhancement

#52 Documentation update for version 2.0.0
  docs/source/developers.rst
  docs/source/downloads/complex_custom_objects/custom_camera_block.py
  docs/source/downloads/complex_custom_objects/custom_path.py
  docs/source/downloads/custom_objects/custom_actuator.py
  docs/source/downloads/custom_objects/custom_block.py
  docs/source/downloads/custom_objects/custom_camera.py
  docs/source/downloads/custom_objects/custom_inout.py
  docs/source/downloads/custom_objects/custom_inout_streamer.py
  docs/source/downloads/custom_objects/custom_modifier.py
  docs/source/features.rst
  docs/source/tutorials/complex_custom_objects.rst
  docs/source/tutorials/custom_objects.rst
  docs/source/tutorials/getting_started.rst
  docs/source/tutorials/more_complexity.rst
  docs/source/what_is_crappy.rst
  examples/custom_objects/custom_actuator.py
Labels: documentation

#53 Add example demonstrating the creation of a custom Camera Block
  docs/source/tutorials/complex_custom_objects.rst
  examples/custom_objects/custom_camera_block.py
Labels: documentation

#54 Simplify the creation of custom Path objects
  docs/source/downloads/complex_custom_objects/custom_path.py
  docs/source/tutorials/complex_custom_objects.rst
  examples/blocks/generator/generator_feedback_loop.py
  examples/custom_objects/custom_generator_path.py
  src/crappy/blocks/generator.py
  src/crappy/blocks/generator_path/conditional.py
  src/crappy/blocks/generator_path/constant.py
  src/crappy/blocks/generator_path/custom.py
  src/crappy/blocks/generator_path/cyclic.py
  src/crappy/blocks/generator_path/cyclic_ramp.py
  src/crappy/blocks/generator_path/integrator.py
  src/crappy/blocks/generator_path/meta_path/path.py
  src/crappy/blocks/generator_path/ramp.py
  src/crappy/blocks/generator_path/sine.py
Labels: enhancement

#56 Update the README files
  README.md
  docs/README.md
  examples/README.md
  setup.py
  src/README.md
  tests/README.md
  util/README.md
Labels: documentation

#55 Enhancement of the parameters management for the gstreamer camera
  CODEOWNERS
  src/crappy/camera/__init__.py
  src/crappy/camera/gstreamer_camera_basic.py
  src/crappy/camera/gstreamer_camera_v4l2.py
Labels: enhancement
